### ISSUE TITLE
Bugfix: Workers don't stick to their boats on the second day

### ISSUE THREAD

**Issue by Guantes188** [barthdamon/FishManager#1]

**Comment by Frictionpowered** [comment]
I just played, it seems to be working

**Comment by Guantes188** [comment]
I think I found some weird code that might explain what I was seeing. I'll take a look at lunch.

**Comment by Frictionpowered** [comment]
I found some nasty bug about the tasks last night (ask Aik:) and ended up fixing it; it involved both equipment and workers, so i think i might have fixed it.
