### ISSUE TITLE
Audience fish  doesn't cast shadow

### ISSUE THREAD

**Issue by aik6980** [barthdamon/FishManager#10]
Audience fish  doesn't cast shadow
can someone help?

**Comment by Frictionpowered** [comment]
i think i've fixed that, but will take a look

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Frictionpowered** [comment]
NOW fixed! :)
Look what a shady figure ;)
[image: image.png]
