### ISSUE TITLE
Feature: Emoji's in chat

### ISSUE THREAD

**Issue by Guantes188** [barthdamon/FishManager#2]
- Add support to text bubbles in game
- Create emoji font?!?

**Comment by aik6980** [comment]
![image](https://user-images.githubusercontent.com/1863381/65492091-3e251380-dea8-11e9-9802-c28c9f5fed09.png)

Emoji is working! :) @Guantes188  @Frictionpowered 
@theMorty  I will come over later today explaining how to modify the texture
