### ISSUE TITLE
Tutorial: Add 2D talking heads to explain the game first steps

### ISSUE THREAD

**Issue by Guantes188** [barthdamon/FishManager#4]
Have Bob and Joe come up with some things that you need to do to get playing
Add 3D text when you drop workers to tell you when more workers are needed in a boat and when you're missing equipment.

**Comment by Frictionpowered** [comment]
How about adding a [Help Me] button (people seem to notice the connect/disconnect/ect) that simple calls DialogManager.Say_2D() with random hints picked from a string array?
Could work exactly the same as when we call in the mafia at the end, except using Jim or Bob. one line of code. (plus adding the button and the hints of course :)
