### ISSUE TITLE
Balance: Double the daylight time

### ISSUE THREAD

**Issue by Guantes188** [barthdamon/FishManager#7]

**Comment by aik6980** [comment]
![image](https://user-images.githubusercontent.com/1863381/65468968-a6023c80-de5d-11e9-9bd8-432011a922b7.png)

I double this variable and it seems to work is it enough? @Guantes188

**Comment by Frictionpowered** [comment]
yep, just checked, it's done

**Comment by Frictionpowered** [comment]
by the way, this also means it takes nearly twice as long to get new workers. is that ok?

**Comment by Guantes188** [comment]
Good call @Frictionpowered ... should we split the difference with 90s?
